# Generated by Django 5.2.1 on 2025-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hesabketab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtTitle', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('hesabketab_type', models.CharField(choices=[('income', 'omad'), ('expense', 'raft')], max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
